# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('fun_facts', models.CharField(max_length=1000)),
                ('production_company', models.CharField(max_length=700)),
                ('distributor', models.CharField(max_length=700)),
                ('director', models.CharField(max_length=700)),
                ('writer', models.CharField(max_length=700)),
                ('actor1', models.CharField(max_length=700)),
                ('actor2', models.CharField(max_length=700)),
                ('actor3', models.CharField(max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Movie'),
        ),
    ]
